### PR TITLE
chore: bump `@trezor/connect-web` to version `9.2.1`

### PR DESCRIPTION
**Pull request by gabrielKerekes**
~~Temporarily fix https://github.com/anza-xyz/wallet-adapter/issues/918.~~

~~Trezor have already created a PR with a fix for the issue - https://github.com/trezor/trezor-suite/pull/11443. I asked how soon they'd release, but haven't gotten a response yet. If it should be today/tomorrow then it's perhaps not worth it to merge this. I'll let you know as soon as I get a response.~~

Bump `@trezor/connect-web` web version to `9.2.1` so that users don't accidentally install version `9.2.0` which would resulted in a broken build of their app.

### CODE REVIEW

**Comment by gabrielKerekes** [comment]
Trezor should release the fix today or tomorrow - https://github.com/trezor/trezor-suite/pull/11443#issuecomment-1978356053.

**Comment by mcintyre94** [comment]
@gabrielKerekes Would you mind bumping this to `^9.2.1` just to make sure nobody picks up the broken dependency going forward?  I'm unsure which dependencies are good/bad between >9.1.6 and <9.2.1, but let's just make sure nobody gets any of them going forward.

**Comment by gabrielKerekes** [comment]
I force-pushed the update to 9.2.1. https://github.com/anza-xyz/wallet-adapter/pull/920/commits/a73d5bc10c7d6baa5b1977a5f1014703d6cb5f54. I also renamed the PR and updated the description for future reference.

Just FYI - it was only version 9.2.0 which was broken.

**Comment by mcintyre94** [comment]
Perfect, thankyou!

**Comment by Mandog1120** [comment]
888a8545a9921e62e8214501aeddd50564482df0

**Pull request merged**
