### PR TITLE
fix: TransportRaceCondition is not found becasue it is renamed to TransportPendingOperation

### PR DESCRIPTION
**Pull request by Kori000**
https://github.com/LedgerHQ/ledger-live/commit/931d511f5c5da86ddee53c69775515da019b6241

 <details>
   <summary>Expaned view</summary>

```
npm why @ledgerhq/errors
@ledgerhq/errors@6.16.4
node_modules/@ledgerhq/errors
  @ledgerhq/errors@"^6.10.0" from @ledgerhq/devices@6.27.1
  node_modules/@ledgerhq/devices
    @ledgerhq/devices@"^6.27.1" from @ledgerhq/hw-transport@6.27.1
    node_modules/@ledgerhq/hw-transport
      @ledgerhq/hw-transport@"^6.27.1" from @ledgerhq/hw-transport-webhid@6.27.1
      node_modules/@ledgerhq/hw-transport-webhid
        @ledgerhq/hw-transport-webhid@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
        node_modules/@solana/wallet-adapter-ledger
          @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
          node_modules/@solana/wallet-adapter-wallets
            @solana/wallet-adapter-wallets@"^0.19.32" from the root project
      @ledgerhq/hw-transport@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
      node_modules/@solana/wallet-adapter-ledger
        @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
        node_modules/@solana/wallet-adapter-wallets
          @solana/wallet-adapter-wallets@"^0.19.32" from the root project
    @ledgerhq/devices@"^6.27.1" from @ledgerhq/hw-transport-webhid@6.27.1
    node_modules/@ledgerhq/hw-transport-webhid
      @ledgerhq/hw-transport-webhid@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
      node_modules/@solana/wallet-adapter-ledger
        @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
        node_modules/@solana/wallet-adapter-wallets
          @solana/wallet-adapter-wallets@"^0.19.32" from the root project
    @ledgerhq/devices@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
    node_modules/@solana/wallet-adapter-ledger
      @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
      node_modules/@solana/wallet-adapter-wallets
        @solana/wallet-adapter-wallets@"^0.19.32" from the root project
  @ledgerhq/errors@"^6.10.0" from @ledgerhq/hw-transport@6.27.1
  node_modules/@ledgerhq/hw-transport
    @ledgerhq/hw-transport@"^6.27.1" from @ledgerhq/hw-transport-webhid@6.27.1
    node_modules/@ledgerhq/hw-transport-webhid
      @ledgerhq/hw-transport-webhid@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
      node_modules/@solana/wallet-adapter-ledger
        @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
        node_modules/@solana/wallet-adapter-wallets
          @solana/wallet-adapter-wallets@"^0.19.32" from the root project
    @ledgerhq/hw-transport@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
    node_modules/@solana/wallet-adapter-ledger
      @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
      node_modules/@solana/wallet-adapter-wallets
        @solana/wallet-adapter-wallets@"^0.19.32" from the root project
  @ledgerhq/errors@"^6.10.0" from @ledgerhq/hw-transport-webhid@6.27.1
  node_modules/@ledgerhq/hw-transport-webhid
    @ledgerhq/hw-transport-webhid@"6.27.1" from @solana/wallet-adapter-ledger@0.9.25
    node_modules/@solana/wallet-adapter-ledger
      @solana/wallet-adapter-ledger@"^0.9.25" from @solana/wallet-adapter-wallets@0.19.32
      node_modules/@solana/wallet-adapter-wallets
        @solana/wallet-adapter-wallets@"^0.19.32" from the root project
```

</details>

### CODE REVIEW

**Comment by devfive** [comment]
https://github.com/LedgerHQ/ledger-live/pull/6394

**Comment by SpiffGreen** [comment]
If this is a fix can it be merged already? 🤲🙏

**Comment by jh-9527** [comment]
How to solve this problem?

**Comment by Devonthib** [comment]
> How to solve this problem?

Adding this to your package.json is a work around.

"overrides": {
    "@ledgerhq/errors": "6.16.3"
  }

**Comment by karangoraniya** [comment]
@Devonthib 

```
"overrides": {
"@ledgerhq/errors": "6.16.3"
}
```
I tried using that version, but I'm still encountering the same error.

```ERROR in ./node_modules/@solana/wallet-adapter-ledger/node_modules/@ledgerhq/hw-transport/lib-es/Transport.js 225:26-48```

**Comment by wakechromium** [comment]
> > How to solve this problem?
> 
> Adding this to your package.json is a work around.
> 
> "overrides": { "@ledgerhq/errors": "6.16.3" }

I'm using yarn and added resolutions but not working.

**Comment by ArlenMor** [comment]
I have the same problem. Have you found a solution?

**Comment by lodiii** [comment]
Still does not work . . .

**Comment by dduo518** [comment]
Still does not work . . .
when to merge this PR。

**Comment by Kori000** [comment]
> > > How to solve this problem?
> > 
> > 
> > Adding this to your package.json is a work around.
> > "overrides": { "@ledgerhq/errors": "6.16.3" }
> 
> I'm using yarn and added resolutions but not working.我使用纱线和添加的决议，但不工作。

Snipaste_2024-05-07_11-48-28

```bash
rm -rf node_modules
npm i --force
```

**Comment by gameuser1982** [comment]
This patch doesn't work when using yarn. What's the work around with Yarn?

**Comment by Kori000** [comment]
> `npm -i force`
> 
> 
> 
> AND
> 
> 
> 
> `pnpm -i force `
> 
> 
> 
>  doesn't work, or I get missing modules:
> 
> 
> 
> ```
> 
> ERROR in ./src/App.tsx 5:0-67
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 6:0-82
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 7:0-89
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react-ui' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 8:0-75
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-wallets' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ```
> 
> 
> 
> These modules aren't missing when I use yarn.
> 
> 
> 
> I am trying to get this working: https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter
> 
> 
> 
> Edit: Also I need to add "@ledgerhq/errors": "6.16.3" to my dependencies too right? 

npm -i force ❌

npm i --force ✅

**Comment by gameuser1982** [comment]
npm i --force results in:

```
npm WARN using --force Recommended protections disabled.
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

npm ERR! A complete log of this run can be found in: /home/candid/.npm/_logs/2024-05-07T20_50_44_378Z-debug-0.log
```
pnpm i --force results in:

```
Failed to compile.

Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
ERROR in ./src/App.tsx 5:0-67
Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'

ERROR in ./src/App.tsx 6:0-82
Module not found: Error: Can't resolve '@solana/wallet-adapter-react' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'

ERROR in ./src/App.tsx 7:0-89
Module not found: Error: Can't resolve '@solana/wallet-adapter-react-ui' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'

ERROR in ./src/App.tsx 8:0-75
Module not found: Error: Can't resolve '@solana/wallet-adapter-wallets' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'

webpack compiled with 4 errors
ERROR in src/App.tsx:1:38
TS2307: Cannot find module '@solana/wallet-adapter-base' or its corresponding type declarations.
  > 1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
      |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
    3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
    4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';

ERROR in src/App.tsx:2:52
TS2307: Cannot find module '@solana/wallet-adapter-react' or its corresponding type declarations.
    1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
  > 2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
      |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
    4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
    5 | import { clusterApiUrl } from '@solana/web3.js';

ERROR in src/App.tsx:3:56
TS2307: Cannot find module '@solana/wallet-adapter-react-ui' or its corresponding type declarations.
    1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
    2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
  > 3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
      |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
    5 | import { clusterApiUrl } from '@solana/web3.js';
    6 | import React, { FC, ReactNode, useMemo } from 'react';

ERROR in src/App.tsx:4:43
TS2307: Cannot find module '@solana/wallet-adapter-wallets' or its corresponding type declarations.
    2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
    3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
  > 4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
      |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    5 | import { clusterApiUrl } from '@solana/web3.js';
    6 | import React, { FC, ReactNode, useMemo } from 'react';
    7 |

```

I am trying to get this working: https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter.

I have been trying to get this to work for the past 10 days. I had a smooth time cross compiling the Solana program into bytecode, but I am really struggling on the frontend side. The react template is completely broken and the person who renamed TransportRaceCondition did not help. 

Do you have any solution?

If not then I am thinking of using Yarn because it actually installs the missing dependencies instead of skipping them and then going into transport.js and changing the function name to the new one. What do you think?

**Comment by gameuser1982** [comment]
I am still getting the error ```
ERROR in ./node_modules/@ledgerhq/hw-transport/lib-es/Transport.js 225:26-48
export 'TransportRaceCondition' (imported as 'TransportRaceCondition') was not found in '@ledgerhq/errors'
```

Even if I replace the TransportRaceCondition import as TransportPendingOperation. Not sure what I am missing here.

**Comment by gameuser1982** [comment]
Hmmm I have been digging deeper. I renamed TransportRaceCondition to TransportPendingOperation in both transport.js, transport.ts, and transport.js.flow and I am still having this compile error.

**Comment by shinebacksoftware** [comment]
@Kori000 I am having the same problem as @gameuser1982. Can you please assist? What kind of god damned idiot decided to rename TransportRaceCondition to TransportPendingOperation? I cannot believe how poorly maintained this repo is!

**Comment by linuxhjkaru** [comment]
For temporarily fix, add below line into file `node_modules/@ledgerhq/hw-transport/node_modules/@ledgerhq/errors/lib-es/index.js`

```
export const TransportRaceCondition = createCustomErrorClass("TransportPendingOperation");
```

**Comment by Kori000** [comment]
> Hmmm I have been digging deeper. I renamed TransportRaceCondition to TransportPendingOperation in both transport.js, transport.ts, and transport.js.flow and everywhere it is associated in @LedgerHQ and I am still having this compile error. Why does it keep giving me this error even though I changed the function call?嗯，我一直在深入挖掘。我在transport.js，transport.ts和transport.js.flow中将TransportRaceCondition重命名为TransportPendingOperation，并且在 @ LedgerHQ中关联的任何地方，我仍然有这个编译错误。为什么它不断给我这个错误，即使我改变了函数调用？



> npm i --force results in:
> 
> ```
> npm WARN using --force Recommended protections disabled.
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:^
> 
> npm ERR! A complete log of this run can be found in: /home/candid/.npm/_logs/2024-05-07T20_50_44_378Z-debug-0.log
> ```
> 
> pnpm i --force results in:
> 
> ```
> Failed to compile.
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> ERROR in ./src/App.tsx 5:0-67
> Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 6:0-82
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 7:0-89
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react-ui' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 8:0-75
> Module not found: Error: Can't resolve '@solana/wallet-adapter-wallets' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> webpack compiled with 4 errors
> ERROR in src/App.tsx:1:38
> TS2307: Cannot find module '@solana/wallet-adapter-base' or its corresponding type declarations.
>   > 1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>       |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
> 
> ERROR in src/App.tsx:2:52
> TS2307: Cannot find module '@solana/wallet-adapter-react' or its corresponding type declarations.
>     1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>   > 2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>       |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>     5 | import { clusterApiUrl } from '@solana/web3.js';
> 
> ERROR in src/App.tsx:3:56
> TS2307: Cannot find module '@solana/wallet-adapter-react-ui' or its corresponding type declarations.
>     1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>   > 3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>       |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>     5 | import { clusterApiUrl } from '@solana/web3.js';
>     6 | import React, { FC, ReactNode, useMemo } from 'react';
> 
> ERROR in src/App.tsx:4:43
> TS2307: Cannot find module '@solana/wallet-adapter-wallets' or its corresponding type declarations.
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>   > 4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>       |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     5 | import { clusterApiUrl } from '@solana/web3.js';
>     6 | import React, { FC, ReactNode, useMemo } from 'react';
>     7 |
> ```
> 
> I am trying to get this working: https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter.
> 
> I have been trying to get this to work for the past 10 days. I had a smooth time cross compiling the Solana program into bytecode, but I am really struggling on the frontend side. The react template is completely broken and the person who renamed TransportRaceCondition did not help.
> 
> Do you have any solution?
> 
> If not then I am thinking of using Yarn because it actually installs the missing dependencies instead of skipping them and then going into transport.js and changing the function being called from TransportRaceCondition to TransportPendingOperation. What do you think?

look like a monorepo error

> @ledgerhq/errors

This seems to be a monorepo issue. If you want to use 
https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter,
you need to follow the [BUILD.md](https://github.com/anza-xyz/wallet-adapter/blob/master/BUILD.md) instructions to start the project. Also, this project uses pnpm, so you can't use yarn.

If you're using Vite, here's a [Vite template](https://github.com/Kori000/sol-wallet-adapter-fixed-example-vite) I've created that works with both npm and pnpm. However, using yarn may cause some issues, which I'll address below.

**Comment by Kori000** [comment]
> npm i --force results in:
> 
> ```
> npm WARN using --force Recommended protections disabled.
> npm ERR! code EUNSUPPORTEDPROTOCOL
> npm ERR! Unsupported URL Type "workspace:": workspace:^
> 
> npm ERR! A complete log of this run can be found in: /home/candid/.npm/_logs/2024-05-07T20_50_44_378Z-debug-0.log
> ```
> 
> pnpm i --force results in:
> 
> ```
> Failed to compile.
> 
> Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> ERROR in ./src/App.tsx 5:0-67
> Module not found: Error: Can't resolve '@solana/wallet-adapter-base' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 6:0-82
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 7:0-89
> Module not found: Error: Can't resolve '@solana/wallet-adapter-react-ui' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> ERROR in ./src/App.tsx 8:0-75
> Module not found: Error: Can't resolve '@solana/wallet-adapter-wallets' in '/home/candid/wallet-adapter/packages/starter/create-react-app-starter/src'
> 
> webpack compiled with 4 errors
> ERROR in src/App.tsx:1:38
> TS2307: Cannot find module '@solana/wallet-adapter-base' or its corresponding type declarations.
>   > 1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>       |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
> 
> ERROR in src/App.tsx:2:52
> TS2307: Cannot find module '@solana/wallet-adapter-react' or its corresponding type declarations.
>     1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>   > 2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>       |                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>     5 | import { clusterApiUrl } from '@solana/web3.js';
> 
> ERROR in src/App.tsx:3:56
> TS2307: Cannot find module '@solana/wallet-adapter-react-ui' or its corresponding type declarations.
>     1 | import { WalletAdapterNetwork } from '@solana/wallet-adapter-base';
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>   > 3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>       |                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>     5 | import { clusterApiUrl } from '@solana/web3.js';
>     6 | import React, { FC, ReactNode, useMemo } from 'react';
> 
> ERROR in src/App.tsx:4:43
> TS2307: Cannot find module '@solana/wallet-adapter-wallets' or its corresponding type declarations.
>     2 | import { ConnectionProvider, WalletProvider } from '@solana/wallet-adapter-react';
>     3 | import { WalletModalProvider, WalletMultiButton } from '@solana/wallet-adapter-react-ui';
>   > 4 | import { UnsafeBurnerWalletAdapter } from '@solana/wallet-adapter-wallets';
>       |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     5 | import { clusterApiUrl } from '@solana/web3.js';
>     6 | import React, { FC, ReactNode, useMemo } from 'react';
>     7 |
> ```
> 
> I am trying to get this working: https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter.
> 
> I have been trying to get this to work for the past 10 days. I had a smooth time cross compiling the Solana program into bytecode, but I am really struggling on the frontend side. The react template is completely broken and the person who renamed TransportRaceCondition did not help.
> 
> Do you have any solution?
> 
> If not then I am thinking of using Yarn because it actually installs the missing dependencies instead of skipping them and then going into transport.js and changing the function being called from TransportRaceCondition to TransportPendingOperation. What do you think?

This seems to be a monorepo issue. If you want to use 
https://github.com/anza-xyz/wallet-adapter/tree/master/packages/starter/create-react-app-starter,
you need to follow the [BUILD.md](https://github.com/anza-xyz/wallet-adapter/blob/master/BUILD.md) instructions to start the project. Also, this project uses pnpm, so you can't use yarn.

If you're using Vite, here's a [Vite template](https://github.com/Kori000/sol-wallet-adapter-fixed-example-vite) I've created that works with both npm and pnpm. However, using yarn may cause some issues, which I'll address below.

**Comment by Kori000** [comment]
Regarding this [Vite template](https://github.com/Kori000/sol-wallet-adapter-fixed-example-vite), yarn v1 only accepts **resolutions** instead of **overrides**. When I added the following to package.json:
```json
"resolutions": {
    "@ledgerhq/errors": "6.16.3"
  }
  ```
  
After removing **node_modules** and **any lock files**, and completing yarn install, starting the project still throws the following error:
 
 ```bash
 export 'TransportRaceCondition' (imported as 'TransportRaceCondition') was not found in '@ledgerhq/errors'
 ```
 
 When I removed the resolutions section from package.json and ran yarn install again, the project ran successfully.

This is a peculiar issue, so I suggest using npm, pnpm, or bun as package managers. If someone can resolve this issue with yarn, then I'd recommend using yarn."

**Comment by coredomain** [comment]
Is there any ETA for this fix to be reviewed and approved for merger if it successfully passes?

**Comment by keolamation** [comment]
seriously, FIX THIS

**Comment by ricardopxlcl** [comment]
I'm getting the same problem, and already try did all the steps here. I'm writing to update the community still had the issue.

> seriously, FIX THIS

**Comment by L-F-Escobar** [comment]
> For temporarily fix, add below line into file `node_modules/@ledgerhq/hw-transport/node_modules/@ledgerhq/errors/lib-es/index.js`
> 
> ```
> export const TransportRaceCondition = createCustomErrorClass("TransportPendingOperation");
> ```

This ended up working as a temp fix

Just .... wow. I got nothing good to say ... Incompetent

**Comment by MuhammedAbdelmukaram** [comment]
Any updates on this... huge headache for the past 4 weeks this has been

**Comment by jordaaash** [comment]
Merged and updated the lockfile in 8748ff507b61eaf65e06439fe4bc5fb27e48f70c. Please let me know if this fixes the issue for you!

**Comment by jordaaash** [comment]
@fulldev100 can you link to a repo with code where you have the issue? We can't see from the screenshot where it occurs.

**Comment by Tilakraj0308** [comment]
> For temporarily fix, add below line into file `node_modules/@ledgerhq/hw-transport/node_modules/@ledgerhq/errors/lib-es/index.js`
> 
> ```
> export const TransportRaceCondition = createCustomErrorClass("TransportPendingOperation");
> ```

Working as a temporary fix for now. Thankyou so much for your help.

**Comment by sponge-babe** [comment]
still getting the same issue `export 'TransportRaceCondition' (imported as 'TransportRaceCondition') was not found in '@ledgerhq/errors'`
image

**Comment by sponge-babe** [comment]
> @fulldev100 can you link to a repo with code where you have the issue? We can't see from the screenshot where it occurs.

it occurs as soon as i write `import * as walletAdapterWallets from "@solana/wallet-adapter-wallets";`

**Comment by sponge-babe** [comment]
ok this worked for me 

- remove node_modules
- remove any lock file
- add the following in package.json
`  "overrides": {
    "@ledgerhq/errors": "6.16.3"
  }`

- run `npm i --force`

But still Please fix this issue ASAP! so i can use it with yarn without any errors

**Comment by mcintyre94** [comment]
@sponge-babe Please can you provide a repo demonstrating this issue? We haven't been able to reproduce it and we're not sure why you and others are seeing it and we're not.

I've created a new NextJS app using only npm, added wallet-adapter and the Ledger wallet (from `@solana/wallet-adapter-wallets`), no overrides etc, and I'm not seeing this issue.

Here's my repo, with step-by-step instructions of what I did: https://github.com/mcintyre94/wallet-adapter-ledger-test

And here's a deployed version where you should be able to connect a ledger wallet (all it has is the multi button): https://ledger-test-grecdvccf-callum-mcintyres-projects.vercel.app

We'd like to help understand and fix this issue, but we need a repo where it's happening because we can't reproduce it ourselves.

**Comment by sponge-babe** [comment]
> @sponge-babe Please can you provide a repo demonstrating this issue? We haven't been able to reproduce it and we're not sure why you and others are seeing it and we're not.
> 
> I've created a new NextJS app using only npm, added wallet-adapter and the Ledger wallet (using `import * from @solana/wallet-adapter-wallets`), no overrides etc, and I'm not seeing this issue.
> 
> Here's my repo, with step-by-step instructions of what I did: https://github.com/mcintyre94/wallet-adapter-ledger-test
> 
> And here's a deployed version where you should be able to connect a ledger wallet (all it has is the multi button): https://ledger-test-grecdvccf-callum-mcintyres-projects.vercel.app
> 
> We'd like to help understand and fix this issue, but we need a repo where it's happening because we can't reproduce it ourselves.

There you go @mcintyre94 , [Ledger-hq-issue-repo](https://github.com/sponge-babe/ledgerhq-issue) 
use `yarn` and my node version is `18.17.1`

**Comment by mcintyre94** [comment]
Thanks, I can repro with `yarn & yarn start` in that repo.

If I add resolutions like this:
```
"resolutions": {
    "@ledgerhq/errors": "6.16.3"
},
```

Then there's a warning from `yarn`:
```
warning Resolution field "@ledgerhq/errors@6.16.3" is incompatible with requested version "@ledgerhq/errors@^6.16.4"
```

But it does seem to resolve to 6.16.3:
```
"@ledgerhq/errors@6.16.3", "@ledgerhq/errors@^6.10.0", "@ledgerhq/errors@^6.16.4":
  version "6.16.3"
  resolved "https://registry.yarnpkg.com/@ledgerhq/errors/-/errors-6.16.3.tgz#646f68cc7e6e8d5126bce1ca06140c5ad963bee8"
  integrity sha512-3w7/SJVXOPa9mpzyll7VKoKnGwDD3BzWgN1Nom8byR40DiQvOKjHX+kKQausCedTHVNBn9euzPCNsftZ9+mxfw==
```

But I still get the error when it starts:
```
ERROR in ./node_modules/@ledgerhq/hw-transport-webhid/node_modules/@ledgerhq/hw-transport/lib-es/Transport.js 242:18-43
```

Now if I search `@ledgerhq/hw-transport` in the yarn lock file it seems to be resolving two versions:
```
"@ledgerhq/hw-transport@6.27.1":
  version "6.27.1"
  resolved "https://registry.yarnpkg.com/@ledgerhq/hw-transport/-/hw-transport-6.27.1.tgz#88072278f69c279cb6569352acd4ae2fec33ace3"
  integrity sha512-hnE4/Fq1YzQI4PA1W0H8tCkI99R3UWDb3pJeZd6/Xs4Qw/q1uiQO+vNLC6KIPPhK0IajUfuI/P2jk0qWcMsuAQ==
  dependencies:
    "@ledgerhq/devices" "^6.27.1"
    "@ledgerhq/errors" "^6.10.0"
    events "^3.3.0"

"@ledgerhq/hw-transport@^6.27.1":
  version "6.30.6"
  resolved "https://registry.yarnpkg.com/@ledgerhq/hw-transport/-/hw-transport-6.30.6.tgz#c6d84672ac4828f311831998f4101ea205215a6d"
  integrity sha512-fT0Z4IywiuJuZrZE/+W0blkV5UCotDPFTYKLkKCLzYzuE6javva7D/ajRaIeR+hZ4kTmKF4EqnsmDCXwElez+w==
  dependencies:
    "@ledgerhq/devices" "^8.3.0"
    "@ledgerhq/errors" "^6.16.4"
    "@ledgerhq/logs" "^6.12.0"
    events "^3.3.0"
```

If I instead add the resolution:
```
"resolutions": {
    "@ledgerhq/hw-transport": "6.27.1"
},
```

Then that fixes the issue. So as a workaround for everyone seeing this, this resolution is probably the best solution.

I'm a bit stumped though, because we have that resolution: https://github.com/anza-xyz/wallet-adapter/blob/8748ff507b61eaf65e06439fe4bc5fb27e48f70c/package.json#L63

We also have that precise version as the dependency of the ledger adapter: https://github.com/anza-xyz/wallet-adapter/blob/8748ff507b61eaf65e06439fe4bc5fb27e48f70c/packages/wallets/ledger/package.json#L39

So I'm not sure how yarn is messing this up TBH, or what we can do to fix this for you in our code. I'm not really familiar with yarn though, so would be keen to hear any ideas.

**Comment by yinchonging** [comment]
> ok this worked for me
> 
> * remove node_modules
> * remove any lock file
> * add the following in package.json
>   `  "overrides": { "@ledgerhq/errors": "6.16.3" }`
> * run `npm i --force`
> 
> But still Please fix this issue ASAP! so i can use it with yarn without any errors

I got a new error in the browser

> Uncaught TypeError: Class extends value /static/media/client.98866d6736d9f36d61b8.cjs is not a constructor or null
    at ./node_modules/@solana/web3.js/lib/index.browser.esm.js (rpc-websocket.ts:16:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/@solana/wallet-adapter-react/lib/esm/ConnectionProvider.js (useWalletModal.tsx:36:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:22:1)
    at fn (hot module replacement:61:1)
    at ./src/App.tsx (bundle.js:16:86)
    at options.factory (react refresh:6:1)

**Comment by edam4m3** [comment]
@yinchonging  Same issue, this project/repo is plagued with issues

**Comment by jordaaash** [comment]
Thanks, everyone. Please move _relevant_ discussion to #950.

**Pull request merged**
