### PR TITLE
Add TokenPocket wallet adapter

### PR DESCRIPTION
**Pull request by chendatony31**
TokenPocket will support solana in the next release after two days.

### CODE REVIEW

**Comment by jordansexton** [comment]
Additionally, please allow commits from maintainers on your fork's master branch so I can update the PR as well. Thanks!

**Comment by chendatony31** [comment]
Yes, as lots of dapps using Phantom as a login option. We are trying to be compatible with it at an early stage. 

I've added you into our fork's master, thank you Jordan.

**Comment by jordansexton** [comment]
The problem isn't that you want to use the same API as Phantom, that's fine. The problem is that the Phantom adapter in this library contains workarounds for issues with Phantom, so you don't necessarily want to copy those parts. I think these things can be removed from the TokenPocket adapter if the TokenPocket wallet doesn't require those workarounds for connection problems.

**Comment by chendatony31** [comment]
Got it, and have removed those code.

**Comment by chendatony31** [comment]
@jordansexton  Hi we've released our new version which supports Solana dapp. You can log in dapps using Phantom option for now, if you want to try. https://tokenpocket.pro/

**Pull request merged**
